<a href="https://colab.research.google.com/github/Zinwaiyan274/Twitter-Sentiment-Analysis/blob/main/Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

#Text processing libraries
import re
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer #feature extraction


#model building
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB

#evaluation metrics
from sklearn.metrics import confusion_matrix,f1_score, precision_score, accuracy_score, ConfusionMatrixDisplay, recall_score

nltk.download('stopwords')
stop_words = set(stopwords.words('english')) 

lemmatizer = WordNetLemmatizer() 

pd.pandas.set_option('display.max_columns',None)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#TF-IDF
vectorizer = TfidfVectorizer(stop_words='english',ngram_range=(1,3),min_df=10,max_features=10000) 

features_train= vectorizer.fit_transform(X_train['Tweet'])

features_valid= vectorizer.transform(X_valid['Tweet'])

features_train.shape, features_valid.shape

((51797, 9076), (22199, 9076))

In [ ]:
#Multinomail Naive Bayes
def model(model):
   
    model.fit(features_train,y_train)
    pred=model.predict(features_valid)
  
    print(model)
    print('Accuracy score: ',accuracy_score(pred,y_valid))
    print('F1 score: ',f1_score(y_pred=pred,y_true=y_valid,average='weighted'))
    print("recall", recall_score(pred,y_valid, average='weighted'))
    print('Precision: ', precision_score(pred,y_valid, average='macro'))
    print('Confusion Matrix: \n',confusion_matrix(pred,y_valid))
    
    
   
nb=MultinomialNB()
model(nb)

MultinomialNB()
Accuracy score:  0.6667867921978468
F1 score:  0.6570664405036415
recall 0.6667867921978468
Precision:  0.6364687639517542
Confusion Matrix: 
 [[1599   86  180  162]
 [ 944 5522 1174  955]
 [ 409  436 3015  444]
 [ 957  600 1050 4666]]


In [ ]:
#Logistic Regression
lr=LogisticRegression(random_state=10,max_iter=600)
pre = model(lr)
pre
# from sklearn.metrics  import confusion_matrix
# confusion_matrix(y_valid, pre)

LogisticRegression(max_iter=600, random_state=10)
Accuracy score:  0.7247173296094419
F1 score:  0.7214644012217224
recall 0.7247173296094419
Precision:  0.7064360570442305
Confusion Matrix: 
 [[2227  209  264  294]
 [ 620 5575  859  746]
 [ 434  425 3603  504]
 [ 628  435  693 4683]]


In [ ]:
#Decision Tree
dt=DecisionTreeClassifier(random_state=10)
model(dt)

DecisionTreeClassifier(random_state=10)
Accuracy score:  0.7913869994143881
F1 score:  0.7912600288746594
recall 0.7913869994143881
Precision:  0.7826887723987173
Confusion Matrix: 
 [[2779  180  206  286]
 [ 325 5440  390  438]
 [ 247  365 4163  317]
 [ 558  659  660 5186]]


In [ ]:
#Random Forest
rf=RandomForestClassifier(random_state=300,n_jobs=-1)
                        # random_state=101 doesn't change Confusion Matrix
model(rf)

RandomForestClassifier(n_jobs=-1, random_state=300)
Accuracy score:  0.881616289022028
F1 score:  0.8817911883486355
recall 0.881616289022028
Precision:  0.873596216232276
Confusion Matrix: 
 [[3156   60   77   89]
 [ 206 6019  211  268]
 [ 124  143 4660  134]
 [ 423  422  471 5736]]


In [ ]:
#Decision Tree
dt=DecisionTreeClassifier(random_state=10)
model(dt)

DecisionTreeClassifier(random_state=10)
Accuracy score:  0.7913869994143881
F1 score:  0.7912600288746594
recall 0.7913869994143881
Precision:  0.7826887723987173
Confusion Matrix: 
 [[2779  180  206  286]
 [ 325 5440  390  438]
 [ 247  365 4163  317]
 [ 558  659  660 5186]]
